name: Create Instagram Reel Container

on:
  workflow_dispatch:

jobs:
  create-container:
    runs-on: ubuntu-latest

    steps:
      - name: Create Reel Container
        run: |
          curl -v "https://graph.instagram.com/me?fields=id,username&access_token=${{ secrets.IG_ACCESS_TOKEN_EN }}" \
          -F "media_type=REELS" \
          -F "video_url=${{ secrets.IG_PUBLIC_VIDEO_URL_EN }}" \
          -F "caption=#popbite #shorts #facts #didyouknow #education #unibite" \
          -F "access_token=${{ secrets.IG_ACCESS_TOKEN_EN }}"
